version: '3.8'
services:
  ephata.db:
    container_name: ephata.db
    image: postgres:13-alpine
    ports:
      - '35000:5432'
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  ephata.backend:
    container_name: ephata.backend
    build: .
    command: sh -c "yarn migrations:run && node dist/main"
    ports:
      - '8080:3000'
    environment:
      DB_PORT: 5432
      DB_HOST: ephata.db
      NODE_ENV: development
      PORT: 3000
    depends_on: 
      - ephata.db

volumes:
  pgdata: