name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: backend
      - name: Build
        run: dotnet build --no-restore
        working-directory: backend
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: backend
        
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
       
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: Install dependencies
        run: npm install
        working-directory: front
      - name: Run tests
        run: npm test
        working-directory: front
      - name: Build
        run: npm run build
        working-directory: front
